title: Linux Shell Life Hacks
author: flattop5377
email: flattop5377@protonmail.com
description: >
  Handy collection of tips and tricks for the command line with a focus on
  system administration tools.
github_username: flattop5377
rss: rss

remote_theme: "jekyll/minima@c6e74bb"
plugins:
  - jekyll-feed
  - jekyll-seo

